#!/bin/bash

set -e
trap 'echo "There is an error in $LINENO, command: $BASH_COMMAND"' ERR

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"


USERID=$(id -u)
LOG_FOLDER="/var/log/shell-script"
LOG_FILE="/var/log/shell-script/$0.log"

if [ $USERID -ne 0 ]; then
    echo -e "$R Please run this command with root user: $N" | tee -a $LOG_FILE
    exit 1
fi

mkdir -p $LOG_FOLDER


for package in $@
do
    dnf list installed $package &>> $LOG_FILE
    if [ $? -ne 0 ]; then
        echo "$package not installed, installing now"
        dnf install $package -y &>> $LOG_FILE
    else
        echo "$package already installed, $Y skipping $N"
    fi
done